id: P009565
initial_creation_type: ocr
source_metadata:
  id: bdr:W5JW1
  title: ༡༦་བོ༹ལུམེ་ཏེརྨིནོལོགིཅལ་ནོཏེབོཨོཀ
  author: ''
  volumes:
    16d4158647704d2eaeb437e42b0080b2:
      image_group_id: I1KG15536
      title: ''
      volume_number: 1
      total_pages: 580
    c3110ad743b54f45952b18c6442e7c18:
      image_group_id: I1KG15537
      title: ''
      volume_number: 2
      total_pages: 280
    224d6f77fe0b4b63af43e1de33e4137e:
      image_group_id: I1KG15538
      title: ''
      volume_number: 3
      total_pages: 574
    eacb37537da144a98d309e5b679fbd58:
      image_group_id: I1KG15539
      title: ''
      volume_number: 4
      total_pages: 702
    b1fc660e94cd492ea8a2b32bcca04a0c:
      image_group_id: I1KG15540
      title: ''
      volume_number: 5
      total_pages: 316
    7ff768682d224fa6bc584fe912ee8a93:
      image_group_id: I1KG15541
      title: ''
      volume_number: 6
      total_pages: 690
    3e8504615d594edba208f99fd2415f07:
      image_group_id: I1KG15542
      title: ''
      volume_number: 7
      total_pages: 690
    9a8c50a431b54b55bc21ca2c0d71ed0d:
      image_group_id: I1KG15543
      title: ''
      volume_number: 8
      total_pages: 422
    ed86b2e147b4421c9a1602022df2b88c:
      image_group_id: I1KG15544
      title: ''
      volume_number: 9
      total_pages: 436
    313ce384d4f54bf2838816d0604c74fa:
      image_group_id: I1KG15545
      title: ''
      volume_number: 10
      total_pages: 522
    9817b105f2ef4862a5fea89f8d309203:
      image_group_id: I1KG15546
      title: ''
      volume_number: 11
      total_pages: 386
    94df8f7067fd4e5795c38e185afa9f79:
      image_group_id: I1KG15547
      title: ''
      volume_number: 12
      total_pages: 702
    54d21bc3a3ba4b4f95bc08606cc1eb87:
      image_group_id: I1KG15548
      title: ''
      volume_number: 13
      total_pages: 680
    eb21f671a1eb49d6a294089cfa51c5fc:
      image_group_id: I1KG15549
      title: ''
      volume_number: 14
      total_pages: 790
    6306a6ed2f5342208cee0750c54da654:
      image_group_id: I1KG15550
      title: ''
      volume_number: 15
      total_pages: 746
    91f827caff514fdca5dac516c3d09984:
      image_group_id: I1KG15551
      title: ''
      volume_number: 16
      total_pages: 184
