id: I8E3444D5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T08:51:58+00:00'
last_modified: '2022-06-08T11:55:57.371013+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W5JW1
  title: ༡༦་བོ༹ལུམེ་ཏེརྨིནོལོགིཅལ་ནོཏེབོཨོཀ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4495':
      image_group_id: I1KG15536
      title: ''
      total_pages: 580
      order: 1
      base_file: 4495.txt
    44FA:
      image_group_id: I1KG15537
      title: ''
      total_pages: 280
      order: 2
      base_file: 44FA.txt
    3B92:
      image_group_id: I1KG15538
      title: ''
      total_pages: 574
      order: 3
      base_file: 3B92.txt
    '4724':
      image_group_id: I1KG15539
      title: ''
      total_pages: 702
      order: 4
      base_file: 4724.txt
    78F0:
      image_group_id: I1KG15540
      title: ''
      total_pages: 316
      order: 5
      base_file: 78F0.txt
    6CFB:
      image_group_id: I1KG15541
      title: ''
      total_pages: 690
      order: 6
      base_file: 6CFB.txt
    6E83:
      image_group_id: I1KG15542
      title: ''
      total_pages: 690
      order: 7
      base_file: 6E83.txt
    C0EB:
      image_group_id: I1KG15543
      title: ''
      total_pages: 422
      order: 8
      base_file: C0EB.txt
    '1640':
      image_group_id: I1KG15544
      title: ''
      total_pages: 436
      order: 9
      base_file: 1640.txt
    A755:
      image_group_id: I1KG15545
      title: ''
      total_pages: 522
      order: 10
      base_file: A755.txt
    052D:
      image_group_id: I1KG15546
      title: ''
      total_pages: 386
      order: 11
      base_file: 052D.txt
    07C9:
      image_group_id: I1KG15547
      title: ''
      total_pages: 702
      order: 12
      base_file: 07C9.txt
    B287:
      image_group_id: I1KG15548
      title: ''
      total_pages: 680
      order: 13
      base_file: B287.txt
    AA92:
      image_group_id: I1KG15549
      title: ''
      total_pages: 790
      order: 14
      base_file: AA92.txt
    ECD6:
      image_group_id: I1KG15550
      title: ''
      total_pages: 746
      order: 15
      base_file: ECD6.txt
    8E45:
      image_group_id: I1KG15551
      title: ''
      total_pages: 184
      order: 16
      base_file: 8E45.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
